name: 同步原仓库更新
on:
  workflow_dispatch:  # 仅保留手动触发（点击“运行工作流”才执行）
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 配置上游仓库
        run: |
          git remote add upstream https://github.com/bmax121/APatch.git
          git fetch upstream
      - name: 合并更新
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories
      - name: 推送代码
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
